"""Session persistence: an append-only transcript per session in .minicc/sessions/.

Each session is a JSONL file (`<id>.jsonl`), written one event per line and NEVER
rewritten — so the raw conversation survives even when the in-memory working set is
compacted (an overwrite-on-save scheme would drop the summarized history). Five event kinds:

    {"t": "msg",     "ts": <iso>, "m": <one API-shaped message>[, "usage": {...}]}
    {"t": "compact", "state": [<messages>]}           # post-compaction working set
    {"t": "rewind",  "state": [<messages>]}           # conversation /rewind reset
    {"t": "context_edit", "edits": [<tool-result replacements>]}
    {"t": "session_counter", "name": <counter>, "delta": <positive int>}

`ts` (every msg) and `usage` (assistant msgs, token counts from the API response)
mirror CC's transcript fields — they're what make post-hoc process analysis
(timing, cost, turn economy) possible. Replay ignores unknown keys, so old
transcripts without them stay loadable.

`load` replays the log: a `msg` event appends; a `compact` or `rewind` event RESETS
the working set to its recorded state (summary + kept tail); a `context_edit`
event replaces selected old tool-result contents. So reconstruction yields
exactly what the live session held — small and API-ready — no matter how long the
raw log grew, while the original `msg` events stay on disk (lossless).

Serialization: assistant messages hold SDK Block objects (TextBlock/ToolUseBlock)
that don't JSON-serialize; `model_dump(exclude_none=True)` yields minimal, API-clean
dicts (dropping SDK-only fields like `caller`/`citations`). Strings and existing
dicts pass through unchanged.
"""

import hashlib
import json
import re
from datetime import datetime
from pathlib import Path
from uuid import uuid4

from minicc import config

_SESSIONS_SUBDIR = ".minicc/sessions"
_TOOL_OUTPUTS_SUBDIR = ".minicc/tool_outputs"
_SESSION_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_COUNTER_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,63}$")


class SessionError(Exception):
    """Base class for failures that prevent safe session access."""


class InvalidSessionIdError(SessionError, ValueError):
    """The supplied session id cannot be represented as one safe file stem."""


class SessionNotFoundError(SessionError, FileNotFoundError):
    """The requested session transcript does not exist."""


class SessionCorruptError(SessionError):
    """The transcript exists but cannot be replayed safely."""


class SessionIOError(SessionError, OSError):
    """The transcript exists but could not be read."""


def _dir() -> Path:
    """Return the sessions directory for the current working directory."""
    return Path.cwd() / _SESSIONS_SUBDIR


def validate_id(session_id: str) -> str:
    """Return a safe opaque session id or raise ``InvalidSessionIdError``.

    UUIDs generated by :func:`new_id` and legacy timestamp ids both satisfy
    this shape. Path separators, traversal components, whitespace, and empty
    ids are rejected before any filesystem access.
    """
    if not isinstance(session_id, str) or not _SESSION_ID.fullmatch(session_id):
        raise InvalidSessionIdError(
            f"invalid session id {session_id!r}: expected 1-128 letters, "
            "digits, '.', '_' or '-' and an alphanumeric first character"
        )
    return session_id


def _path(session_id: str) -> Path:
    """Return the JSONL transcript path for ``session_id``.

    Args:
        session_id: Session identifier (file stem).

    Returns:
        Path to ``<session_id>.jsonl`` under the sessions directory.
    """
    session_id = validate_id(session_id)
    root = _dir().resolve()
    candidate = (root / f"{session_id}.jsonl").resolve()
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise InvalidSessionIdError(
            f"session id {session_id!r} escapes the sessions directory"
        ) from error
    return candidate


def path(session_id: str | None) -> Path | None:
    """Return the public transcript path for a session, or None if unset.

    Hooks expose this as ``transcript_path`` in their stdin payload (CC parity).

    Args:
        session_id: Session id, or None when there is no session.

    Returns:
        Transcript path, or None when ``session_id`` is None.
    """
    return _path(session_id) if session_id else None


def _safe_component(value: str, fallback: str) -> str:
    """Make an opaque id safe for use as one path component."""
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._")
    return safe[:48] or fallback


def tool_result_output_path(
    session_id: str,
    tool_use_id: str,
    content,
) -> Path:
    """Return the deterministic spill path for one evicted tool result."""
    safe_session = _safe_component(session_id, "session")
    safe_tool = _safe_component(tool_use_id, "tool-result")
    digest = hashlib.sha256(tool_use_id.encode("utf-8")).hexdigest()[:10]
    suffix = ".txt" if isinstance(content, str) else ".json"
    return (
        Path.cwd()
        / _TOOL_OUTPUTS_SUBDIR
        / safe_session
        / f"{safe_tool}-{digest}{suffix}"
    )


def persisted_tool_result_marker(output_path: Path) -> str:
    """Build the in-context pointer left after a tool result is spilled."""
    return (
        "<persisted-output>\n"
        f"Full tool result saved to: {output_path}\n"
        "Use read_file on this path to inspect the full result.\n"
        "</persisted-output>"
    )


def persist_tool_result_output(
    session_id: str,
    tool_use_id: str,
    content,
) -> Path:
    """Persist an evicted result outside active context and return its path."""
    config.ensure_project_dir("tool_outputs")
    output_path = tool_result_output_path(session_id, tool_use_id, content)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        serialized = content
    else:
        serialized = json.dumps(
            content,
            ensure_ascii=False,
            indent=2,
            default=str,
        )
    output_path.write_text(serialized, encoding="utf-8")
    return output_path


def new_id() -> str:
    """Allocate a collision-resistant UUID session id.

    Returns:
        A lowercase UUID4 string. Legacy timestamp ids remain loadable.
    """
    return str(uuid4())


def _serialize_message(m) -> dict:
    """Convert one message into a JSON-serializable, API-clean dict.

    SDK Block objects become ``model_dump(exclude_none=True)`` dicts; plain
    strings and existing dicts pass through. Unknown block types raise so a
    non-round-trippable repr is never written.

    Args:
        m: Message dict with ``role`` and ``content``.

    Returns:
        Dict with ``role`` and serialized ``content``.

    Raises:
        TypeError: A content block is neither a dict nor an SDK model.
    """
    content = m.get("content")
    if isinstance(content, list):
        blocks = []
        for b in content:
            if isinstance(b, dict):
                blocks.append(b)
            elif hasattr(b, "model_dump"):
                blocks.append(b.model_dump(exclude_none=True))
            else:
                raise TypeError(
                    f"un-serializable block in message content: {type(b).__name__}"
                )
        return {"role": m["role"], "content": blocks}
    return {"role": m["role"], "content": content}


def _serialize_messages(messages) -> list:
    """Serialize a list of messages for transcript storage.

    Args:
        messages: Iterable of message dicts.

    Returns:
        List of JSON-serializable message dicts (see ``_serialize_message``).
    """
    return [_serialize_message(m) for m in messages]


def _append_event(session_id: str, event: dict) -> None:
    """Append one JSON event line to the session transcript.

    Args:
        session_id: Target session id.
        event: Event dict to serialize as one JSONL line.
    """
    config.ensure_project_dir("sessions")
    with _path(session_id).open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")


def append_message(session_id: str, message, usage=None, meta=False) -> None:
    """Append one conversation message to the transcript.

    Writes an append-only ``msg`` event in conversation order. ``usage`` and
    ``meta`` ride the transcript record only — never the API message body.

    Args:
        session_id: Target session id.
        message: API-shaped message (may contain SDK Block objects).
        usage: Optional API usage object (assistant turns). Records
            ``input_tokens``, ``output_tokens``, ``cache_read_input_tokens``,
            and ``cache_creation_input_tokens`` for cost analysis.
        meta: If True, mark a harness expansion (slash-command rendered
            content). Matches CC's ``isMeta`` on the second record of a
            tags + expansion pair.
    """
    event = {
        "t": "msg",
        "ts": datetime.now().isoformat(timespec="seconds"),
        "m": _serialize_message(message),
    }
    if meta:
        event["meta"] = True
    if usage is not None:
        event["usage"] = {
            k: getattr(usage, k, 0) or 0
            for k in (
                "input_tokens",
                "output_tokens",
                "cache_read_input_tokens",
                "cache_creation_input_tokens",
            )
        }
    _append_event(session_id, event)


def log_compaction(session_id: str, working_set) -> None:
    """Record a compaction boundary with the post-compaction working set.

    On load, a ``compact`` event resets reconstructed history to this state.
    Earlier ``msg`` events remain on disk (lossless) but do not re-inflate the
    working set.

    Args:
        session_id: Target session id.
        working_set: Messages after compaction (summary + kept tail).
    """
    _append_event(
        session_id, {"t": "compact", "state": _serialize_messages(working_set)}
    )


def log_context_edit(session_id: str, replacements) -> None:
    """Record tool-result replacements without copying the full working set.

    The original result remains in its earlier ``msg`` event. Replay applies this
    delta so resume matches the live working set, while replaying to a point
    before the edit restores the original result.
    """
    edits = [
        {
            "tool_use_id": replacement["tool_use_id"],
            "content": replacement["content"],
        }
        for replacement in replacements
    ]
    if edits:
        _append_event(session_id, {"t": "context_edit", "edits": edits})


def log_rewind(session_id: str, working_set) -> None:
    """Record a conversation rewind with the post-rewind working set.

    Replay resets to this state like ``compact``. Rewound-away messages stay
    on disk because the transcript is append-only.

    Args:
        session_id: Target session id.
        working_set: Messages after the rewind.
    """
    _append_event(
        session_id, {"t": "rewind", "state": _serialize_messages(working_set)}
    )


def record_counter(session_id: str, name: str, delta: int = 1) -> None:
    """Durably increment one session-wide lifecycle counter.

    Counter events are append-only and intentionally survive conversation
    rewind: consumed WebSearch and subagent budgets belong to the session, not
    to the current replayed working set.
    """
    if not isinstance(name, str) or not _COUNTER_NAME.fullmatch(name):
        raise ValueError(f"invalid session counter name: {name!r}")
    if not isinstance(delta, int) or isinstance(delta, bool) or delta <= 0:
        raise ValueError("session counter delta must be a positive integer")
    _append_event(
        session_id,
        {"t": "session_counter", "name": name, "delta": delta},
    )


def counter_totals(session_id: str) -> dict[str, int]:
    """Return accumulated session counters without replaying conversation state."""
    transcript = _path(session_id)
    if not transcript.exists():
        return {}
    totals: dict[str, int] = {}
    for event in _read_events(transcript):
        if event.get("t") != "session_counter":
            continue
        name = event.get("name")
        delta = event.get("delta")
        if (
            not isinstance(name, str)
            or not _COUNTER_NAME.fullmatch(name)
            or not isinstance(delta, int)
            or isinstance(delta, bool)
            or delta <= 0
        ):
            raise SessionCorruptError(
                f"session {session_id!r} contains an invalid counter event"
            )
        totals[name] = totals.get(name, 0) + delta
    return totals


def event_count(session_id: str) -> int:
    """Count events currently in the transcript.

    Checkpoints record this at turn start so a conversation rewind can replay
    back to that position.

    Args:
        session_id: Target session id.

    Returns:
        Number of non-empty JSONL lines, or 0 if the file is missing.
    """
    transcript = _path(session_id)
    if not transcript.exists():
        return 0
    return len(_read_events(transcript))


def latest_id() -> str | None:
    """Return the most recently modified session id in this cwd.

    Returns:
        Session id (file stem), or None if no transcripts exist.
    """
    d = _dir()
    if not d.exists():
        return None
    files = sorted(d.glob("*.jsonl"), key=lambda p: p.stat().st_mtime, reverse=True)
    for transcript in files:
        try:
            return validate_id(transcript.stem)
        except InvalidSessionIdError:
            continue
    return None


def _read_events(transcript: Path, upto: int | None = None) -> list[dict]:
    """Read complete JSONL events, tolerating only an interrupted final append.

    A process can die after writing part of the last line but before its newline.
    If that final unterminated line cannot decode as UTF-8 or JSON, it is ignored.
    Corruption in any earlier line, or in a newline-terminated final line, raises
    ``SessionCorruptError`` instead of silently converting the session to empty.
    """
    try:
        raw = transcript.read_bytes()
    except OSError as error:
        raise SessionIOError(
            f"could not read session transcript {transcript}: {error}"
        ) from error

    raw_lines = raw.splitlines(keepends=True)
    nonempty = [i for i, line in enumerate(raw_lines) if line.strip()]
    last_nonempty = nonempty[-1] if nonempty else None
    events: list[dict] = []
    for index, raw_line in enumerate(raw_lines):
        if upto is not None and len(events) >= upto:
            break
        if not raw_line.strip():
            continue
        final_unterminated = (
            index == last_nonempty and not raw_line.endswith((b"\n", b"\r"))
        )
        try:
            line = raw_line.decode("utf-8").strip()
            event = json.loads(line)
        except (UnicodeDecodeError, json.JSONDecodeError) as error:
            if final_unterminated:
                break
            raise SessionCorruptError(
                f"session transcript {transcript} is corrupt at line {index + 1}: "
                f"{error}"
            ) from error
        if not isinstance(event, dict):
            raise SessionCorruptError(
                f"session transcript {transcript} has a non-object event "
                f"at line {index + 1}"
            )
        events.append(event)
    return events


def _replay(events) -> list:
    """Replay transcript events into a working-set message list.

    ``msg`` appends; ``compact`` and ``rewind`` replace the working set with
    their recorded ``state``; ``context_edit`` applies tool-result deltas.
    Always runs dangling-``tool_use`` repair on the result.

    Args:
        events: Parsed transcript event dicts.

    Returns:
        API-ready working-set messages (dict form).
    """
    working: list = []
    for position, event in enumerate(events, 1):
        event_type = event.get("t")
        if event_type == "msg":
            message = event.get("m")
            if not isinstance(message, dict) or not {"role", "content"} <= message.keys():
                raise SessionCorruptError(
                    f"session transcript has an invalid msg event at position {position}"
                )
            working.append(message)
        elif event_type in ("compact", "rewind"):
            state = event.get("state")
            if not isinstance(state, list) or not all(
                isinstance(message, dict) for message in state
            ):
                raise SessionCorruptError(
                    f"session transcript has an invalid {event_type} event "
                    f"at position {position}"
                )
            working = list(state)
        elif event_type == "context_edit":
            edits = event.get("edits")
            if not isinstance(edits, list):
                raise SessionCorruptError(
                    "session transcript has an invalid context_edit event "
                    f"at position {position}"
                )
            _apply_context_edit(working, edits)
    return _repair_dangling_tool_uses(working)


def _apply_context_edit(messages: list, edits: list) -> None:
    """Apply transcript tool-result replacements to a replayed working set."""
    replacements = {
        edit.get("tool_use_id"): edit.get("content")
        for edit in edits
        if edit.get("tool_use_id")
    }
    if not replacements:
        return
    for message in messages:
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "tool_result":
                continue
            tool_use_id = block.get("tool_use_id")
            if tool_use_id in replacements:
                block["content"] = replacements[tool_use_id]


def _repair_dangling_tool_uses(msgs: list) -> list:
    """Ensure every ``tool_use`` has a matching ``tool_result`` in the next message.

    The API 400s on unanswered ``tool_use`` ids. Older transcripts (e.g. mid
    ``tool_use`` cut by ``max_tokens``) may lack results; this inserts or merges
    synthetic ``tool_result`` blocks so resume can proceed.

    Args:
        msgs: Replayed working-set messages.

    Returns:
        A new list that is API-valid for tool-use pairing. May mutate the
        content list of an existing next user message when merging partial
        results.
    """
    out: list = []
    for i, m in enumerate(msgs):
        out.append(m)
        if m.get("role") != "assistant" or not isinstance(m.get("content"), list):
            continue
        ids = [
            b.get("id")
            for b in m["content"]
            if isinstance(b, dict) and b.get("type") == "tool_use"
        ]
        if not ids:
            continue
        nxt = msgs[i + 1] if i + 1 < len(msgs) else None
        answered = set()
        next_has_results = (
            nxt is not None
            and nxt.get("role") == "user"
            and isinstance(nxt.get("content"), list)
            and any(
                isinstance(b, dict) and b.get("type") == "tool_result"
                for b in nxt["content"]
            )
        )
        if next_has_results:
            answered = {
                b.get("tool_use_id")
                for b in nxt["content"]
                if isinstance(b, dict) and b.get("type") == "tool_result"
            }
        missing = [t for t in ids if t not in answered]
        if not missing:
            continue
        synthetic = [
            {
                "type": "tool_result",
                "tool_use_id": t,
                "content": "[interrupted: no result was recorded]",
            }
            for t in missing
        ]
        if next_has_results:
            # partial answers exist: ALL results must live in that one next
            # message, so merge the synthetic ones into it
            nxt["content"] = list(nxt["content"]) + synthetic
        else:
            out.append({"role": "user", "content": synthetic})
    return out


def _load(session_id: str, upto: int | None) -> list:
    """Load and replay a session transcript into a working set.

    Args:
        session_id: Session to load.
        upto: If set, replay only the first ``upto`` events; otherwise the
            full transcript.

    Returns:
        Dict-form, API-ready messages. A valid empty transcript returns ``[]``.

    Raises:
        InvalidSessionIdError: ``session_id`` is not a safe file stem.
        SessionNotFoundError: No transcript exists for ``session_id``.
        SessionCorruptError: A complete event cannot be decoded or replayed.
        SessionIOError: The transcript cannot be read.
    """
    transcript = _path(session_id)
    if not transcript.is_file():
        raise SessionNotFoundError(f"session {session_id!r} was not found")
    return _replay(_read_events(transcript, upto=upto))


def load(session_id: str) -> list:
    """Load a session's full working set (``--continue`` / ``--resume``).

    Args:
        session_id: Session to load.

    Returns:
        Replayed working-set messages. See :func:`_load` for raised errors.
    """
    return _load(session_id, upto=None)


def load_upto(session_id: str, n_events: int) -> list:
    """Load the working set as of the first ``n_events`` transcript events.

    Used by conversation rewind. Replaying (not slicing live history) works
    across compaction boundaries.

    Args:
        session_id: Session to load.
        n_events: Number of leading transcript events to replay.

    Returns:
        Replayed working-set messages. See :func:`_load` for raised errors.
    """
    if n_events < 0:
        raise ValueError("n_events must be non-negative")
    return _load(session_id, upto=n_events)
